### ISSUE TITLE
FAT lib selection question

### ISSUE THREAD

**Issue by deltabeard** [WRansohoff/SQLite3_STM32_SDMMC#1]
Hello,

Out of curiosity, I was wondering why you have chosen to use the [Gristle](https://github.com/hairymnstr/gristle) FAT library as opposed to [FatFs](http://elm-chan.org/fsw/ff/00index_e.html) or [PetitFs](https://elm-chan.org/fsw/ff/00index_p.html) (both links down at time of writing). Any speed or size benefits that you know of?

Thanks.

**Comment by WRansohoff** [comment]
Honestly, it just looked simple to integrate and I'm more interested in learning about the STM32 SD/MMC card interface and getting something working so that I can build a library that depends on SQLite.

FatFs does look like a good option - ST even ships it with their 'Cube' HAL layers - but right now I'm looking for simplicity. Also, Gristle has a very small reference implementation targeting SD cards using the STM32's SPI interface.

Long-term, it would probably be better to leave the filesystem-related calls as un-implemented stubs that the calling application needs to provide, but right now I'm just seeing if the basic idea is workable.

So to answer your question, I don't have any particularly good reasons for choosing it over other libraries. Thanks for the suggestions, it's good to know about other options.

**Comment by deltabeard** [comment]
Thanks for the reply.
